# Generated by Django 6.0.3 on 2026-03-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Work', 'Work'), ('Alert', 'Alert'), ('Newsletter', 'Newsletter'), ('Personal', 'Personal'), ('Other', 'Other')], default='Other', max_length=50)),
                ('action_required', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
