# Generated by Django 6.0.3 on 2026-03-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
