# Generated by Django 6.0.3 on 2026-03-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0002_emailmessage_gmail_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='is_archived',
        ),
    ]
